const margin = 50;
var gameState;
let trocaInimigo = true;
let inimigoAtual = 0;
let imagemCenario;
let imagemPersonagem;
let imagemVida;
let inimigo;
let inimigoVoador;
let inimigoVoador2;
let inimigoPorco;
let cenarioF1P1;
let cenarioF1P2;
let cenarioF1P3;
let cenarioF2P1;
let cenarioF2P2;
let cenarioF2P3;
let cenarioF3P1;
let cenarioF3P2;
let cenarioF3P3;
let cenarioHomeScreen;
let levelSelector;
let personagem;
let somJogo;
let inimigos;
let configFase1;
let scale = 0.5;
let sceneNumber = 0;
let imagemInvertedButtonPlay;
